- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx  

- name: Ensure Nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes
